- hosts: localhost
  name: Install OCS, 3scale and RHSSO
  vars:
      three_scale_project: 3scale-mw
      insecure_skip_tls_verify: true
      storage_class: gp2
      storage_size: 512Gi
      storage_class_3scale: ocs-storagecluster-cephfs
      wildcardDomain: apps.cluster-2205.2205.example.opentlc.com
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: false

    # - name: Evaluate {{ 3scale_project }} Namespace
    #   when: not delete_demo
    #   k8s:
    #     state: present
    #     kind: Project
    #     api_version: project.openshift.io/v1
    #     definition:
    #       metadata:
    #         name: "{{ demo_project }}"
    #         annotations:
    #           openshift.io/description: "Namespace used in Kafka-keycloak Demo"
    #           openshift.io/display-name: "Kafka-keycloakProject"

    # - name: Evaluate Operator Group
    #   when: not delete_demo
    #   k8s:
    #     state: present
    #     api_version: operators.coreos.com/v1
    #     kind: OperatorGroup
    #     definition:
    #       metadata:
    #         name: '{{ demo_project }}-operatorgroup'
    #         namespace: '{{ demo_project}}'
    #       spec:
    #         targetNamespaces:
    #         - '{{ demo_project }}'

#    - name: Include OCS role
#      include_role:
#        name: ocs

    - name: Include 3Scale role
      include_role:
        name: 3scale

    # - name: Include Apps role
    #   include_role:
    #     name: apps

    # - name: Include LDAP role
    #   include_role:
    #     name: ldap