- name: Evaluate Machines are Running
  shell: oc get machinesets -n openshift-machine-api -o=custom-columns=NAME:.metadata.name | tail -n +2
  register: machinesets_list

- debug: 
    var: machinesets_list

- name: Scale up to 2 replicas the Machines
  shell: 'oc scale --replicas=2 machineset {{ item }} -n openshift-machine-api'
  with_items: "{{ machinesets_list.stdout_lines }}"


- name: Wait for machines to be ready
  shell: "oc get machine -n openshift-machine-api -o json"
  register: machines
  until: machines.stdout|from_json|json_query('items[*].status.phase')|unique == ["Running"]
  retries: 15
  delay: 30


- name: Verify if OCS is installed
  shell: oc get csv -n openshift-storage -o name | grep ocs-operator
  register: ocs_is_installed

# - name: Deploy OCS on Openshift
#   shell: oc apply -f roles/ocs/templates/deploy-with-olm.yaml.j2
#   ignore_errors: True
#   when: ocs_is_installed != ""

- name: Deploy OCS on Openshift
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'storagecluster.yaml.j2') }}"


- name: List the last 3 Machines was created
  shell: oc get nodes -n openshift-machine-api -o=custom-columns=NAME:.metadata.name --sort-by='{.metadata.creationTimestamp}' --no-headers | tail -n 3 | tac
  register: list_last_3nodes

- name: Label Nodes
  shell: "oc label nodes {{ item }} cluster.ocs.openshift.io/openshift-storage='' --overwrite=true"
  with_items: "{{ list_last_3nodes.stdout_lines }}"


- name: Create a StorageCluster
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'storagecluster.yaml.j2') }}"

- name: GET
  shell: "oc get storageclusters.ocs.openshift.io -n openshift-storage -o=custom-columns=.STATUS:status.phase --no-headers"
  register: aaa

- debug: 
    var: aaa.stdout


- name: Wait until the StorageCluster be created
  shell: "oc get storageclusters.ocs.openshift.io -n openshift-storage -o=custom-columns=.STATUS:status.phase --no-headers"
  register: storage_cluster
  until: storage_cluster.stdout == "Ready"
  retries: 15
  delay: 30    
